import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ProtocolContextProvider } from "../../context/ProtocolContext";
import { SessionContextProvider } from "../../context/SessionContext";

import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-bold h-screen w-screen overflow-x-hidden`}
      >
        <Toaster
          theme="dark"
          position="top-center"
          duration={1600}
          expand={false}
        />
        <SessionContextProvider>
          <ProtocolContextProvider>{children}</ProtocolContextProvider>
        </SessionContextProvider>
      </body>
    </html>
  );
}
